// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TerebiToKiroku.Migrations;

#nullable disable

namespace TerebiToKiroku.Migrations.Migrations
{
    [DbContext(typeof(TerebiToKirokuDbContext))]
    [Migration("20260710154821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TerebiToKiroku.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("TerebiToKiroku.Domain.Entities.WatchSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionDuration")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<int>("WatchedDuration")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("WatchSessions");
                });

            modelBuilder.Entity("TerebiToKiroku.Domain.Entities.WatchSession", b =>
                {
                    b.HasOne("TerebiToKiroku.Domain.Entities.Video", null)
                        .WithMany("WatchSessions")
                        .HasForeignKey("VideoId");
                });

            modelBuilder.Entity("TerebiToKiroku.Domain.Entities.Video", b =>
                {
                    b.Navigation("WatchSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
